Run migrations on each deploy

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -7,6 +7,7 @@ source '.environment';
 
 test ! -z "$FTP_USER" || { echo "FTP_USER environment variable is required but not present or empty, aborting."; exit; }
 test ! -z "$FTP_PASSWORD" || { echo "FTP_PASSWORD environment variable is required but not present or empty, aborting."; exit; }
+test ! -z "$MIGRATION_TOKEN" || { echo "MIGRATION_TOKEN environment variable is required but not present or empty, aborting."; exit; }
 
 echo "Deployment started";
 
@@ -32,5 +33,7 @@ mkdir -pf /www/stravid/public/datsu-backend/app/storage/views/
 chmod -Rf 0777 /www/stravid/public/datsu-backend/app/storage
 
 EOF
+
+curl -X POST http://localhost:8000/migrate/$MIGRATION_TOKEN
 
 echo "Deployment finished";
